[RMM-51076] - Fix ArrayOutOfIndex error, headerType=17]
ContinuumLLC/godep-go-smbios pull request #9
Opened 2019-11-22 07:10 UTC by continuum-gufran-baig

2019-11-22 07:41 UTC, continuum-milind-adpaiker approved these changes

2019-11-22 08:47 UTC, KedarB requested changes
We need to check for the manufacturer name & serial number issues, before merging.

2019-11-22 08:50 UTC, continuum-gufran-baig commented
> We need to check for the manufacturer name & serial number issues, before merging.

Manufacturer and Serial number is blank in some systems, need to be verified before merging

2019-11-25 12:27 UTC, KedarB approved these changes

2019-11-26 12:19 UTC, merged